#Enter your Bot token here!
TOKEN: "TOKEN"
#Channel in which messages will be sent in
CHANNEL: "CHANNEL"
CHANNEL-FIND-MODE: "string"
#Post messages in the discord chat into the server
DO_TWO_WAY_CHAT: false
#More to come in config lol
FORMATTING: ""