#Enter your Bot token here!
TOKEN: "TOKEN"
#Channel in which messages will be sent in
CHANNEL: "CHANNEL"
#How to find the channel, 2 options are available - id, string, in id mode, you put the channels id in the CHANNEL field, in string mode, you put the channel name, with exact capitalization and without the #
CHANNEL-FIND-MODE: "string"
#Post messages in the discord chat into the minecraft server
DO-TWO-WAY-CHAT: false
#Custom Message Formatting!
CHAT-FORMATTING: "**$PLAYER_NAME**: $PLAYER_MESSAGE"
#Post a message when player joins
POST-JOIN-MESSAGE: true
#Post a message when player leaves
POST-LEAVE-MESSAGE: true
#Post a message on server startup (Notworking)
POST-SERVER-STARTUP-MESSAGE: true
#Post a message on server shutdown (Notworking)
POST-SERVER-SHUTDOWN-MESSAGE: true
#Formatting for join message
JOIN-FORMATTING: "**$PLAYER_NAME** joined the game."
#Formatting for leave message
LEAVE-FORMATTING: "**$PLAYER_NAME** left the game."