#Enter your Bot token here!
TOKEN: "TOKEN"
#Channel in which messages will be sent in
CHANNEL: "CHANNEL"
#How to find the channel, 2 options are available - id, string, in id mode, you put the channels id in the CHANNEL field, in string mode, you put the channel name, with exact capitalization and without the #
CHANNEL-FIND-MODE: "string"
#Post messages in the discord chat into the minecraft server
DO-TWO-WAY-CHAT: true
#Post a message when player joins
POST-JOIN-MESSAGE: true
#Post a message when player leaves
POST-LEAVE-MESSAGE: true
#Post a message on server startup
POST-SERVER-STARTUP-MESSAGE: true
#Post a message on server shutdown
POST-SERVER-SHUTDOWN-MESSAGE: true
#Post a message if player earns advancement
POST-ADVANCEMENT-EARN-MESSAGE: true
#Post a message when player dies
POST-PLAYER-DEATH-MESSAGE: true
#Wheather or not to use nicknames in 2 way chat
USE-NICKS-IN-2-WAY-CHAT: false
#Use multiple channels to post/receive messages from
#Please note that this may be less performant
MULTICHANNEL-MODE: false
#Channels for MULTICHANNEL Posting
#Please note the channel in the CHANNEL field will not be ignored
MULTICHANNEL-CHANNELS: ["id1","id2","id3","you can go on an on with the number of channels"]
#Formatting for chat message
CHAT-FORMATTING: "**$PLAYER_NAME**: $PLAYER_MESSAGE"
#Formatting for join message
JOIN-FORMATTING: "**$PLAYER_NAME** joined the game."
#Formatting for leave message
LEAVE-FORMATTING: "**$PLAYER_NAME** left the game."
#Formatting for shutdown message
SHUTDOWN-FORMATTING: "**Shutting down server.**"
#Formatting for startup message
STARTUP-FORMATTING: "**Server started.**"

#Any Questions about this plugin , want to suggest a feature or need help?
#Join my discord server https://discord.gg/geNRqMu5XW and ping me(PugzAreCute#4636) in #general
#I will help you as soon as I have time :)
#Any bugs? Please report in in my discord server or on the issue tracker - https://github.com/PugsMods/ServerLink/issues
